### ISSUE TITLE
The Role essential_docker adds unneccessary complexity to variables and unwanted cohesion to other roles

### ISSUE THREAD

**Issue by quantumfate** [quantumfate/quantumhome#1]
The tasks in this role exit solely because I was trying to implement a docker role myself in the past but then opted for using [@geerlingsguy](https://github.com/geerlingguy) well tested docker role. The leftover tasks that are necessary for my implementation are causing unwanted cohesion between roles which defeats the purpose of Ansible roles.

All of the defined tasks run on hosts that should use docker with persistant storage but only one task is restoring the data from backup storage - this task obviously doesn't apply to all hosts
```yaml
  - name: Restore the "{{ docker_dir }}" folder from the MergerFS array
    synchronize:
      src: "{{ mergerfs_root }}/docker_data/data"
      dest: "{{ docker_dir }}/"
      delete: true
      recursive: yes
    delegate_to: "{{ inventory_hostname }}"
    when: persistent_data_find.matched < 20 or not persistent_data.stat.exists
    ignore_errors: true
```

- [x] Rename enable_nas_stuff to host_has_persistant_data
- [x] Move the variable to host specific declaration
- [x] Refactor the mentioned task to only be executed when host has persistant data and backup storage is defined
- [x] Rename the src for the backup to a generic default variable
